### ISSUE TITLE
Crash on Facebook video

### ISSUE THREAD

**Issue by teknico** [otium/ytdl#7]
Yeah, it's not on YouTube, but is seems interesting anyway:

```
$ ytdl https://www.facebook.com/video.php?v=10153820411888896
INFO[0000] Fetching video info...                       
panic: regexp: Compile(`yt.setConfig('PLAYER_CONFIG', (.*?)</script>`): error parsing regexp: missing closing ): `yt.setConfig('PLAYER_CONFIG', (.*?)</script>`

goroutine 1 [running]:
regexp.MustCompile(0x8dcf80, 0x2c, 0xc8204e2000)
	/usr/local/go/src/regexp/regexp.go:221 +0x16f
github.com/otium/ytdl.getInfoFromHTML(0x7ffeafafd0ae, 0x11, 0xc8204e2000, 0x3fc7, 0x7e00, 0x0, 0x0, 0x0)
	/home/nl/go-code/src/github.com/otium/ytdl/info.go:173 +0x265e
github.com/otium/ytdl.GetInfoFromID(0x7ffeafafd0ae, 0x11, 0x0, 0x0, 0x0)
	/home/nl/go-code/src/github.com/otium/ytdl/info.go:91 +0x4c8
github.com/otium/ytdl.GetInfoFromURL(0xc8200a2700, 0x36, 0x0, 0x0)
	/home/nl/go-code/src/github.com/otium/ytdl/info.go:69 +0xfb
github.com/otium/ytdl.GetInfo(0x73c1c0, 0xc820102ad0, 0xc820102ad0, 0x0, 0x0)
	/home/nl/go-code/src/github.com/otium/ytdl/info.go:57 +0x16d
main.handler(0x7ffeafafd089, 0x36, 0x0, 0xc82000bde0, 0x13, 0x0, 0xc820014bc0, 0x4, 0x4, 0x0, ...)
	/home/nl/go-code/src/github.com/otium/ytdl/cmd/ytdl/main.go:147 +0x340
main.main.func1(0xc8200f79e0)
	/home/nl/go-code/src/github.com/otium/ytdl/cmd/ytdl/main.go:109 +0x592
github.com/codegangsta/cli.(*App).Run(0xc8200f78c0, 0xc82000a5a0, 0x2, 0x2, 0x0, 0x0)
	/home/nl/go-code/src/github.com/codegangsta/cli/app.go:180 +0x1051
main.main()
	/home/nl/go-code/src/github.com/otium/ytdl/cmd/ytdl/main.go:112 +0x10b4

[...]
```

**Comment by otium** [comment]
The regex for extracting info json from embedded youtube urls was invalid, fixed in 1bd6f28a0aaa046572a0fa22d7aa5b4e2c1908b3.
